name: Scheduled API Tests

on:
  schedule:
    - cron: '38 6,18 * * *'  # UTC'ye göre sabah ve akşam 09:34 (Türkiye saati UTC+3)

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Kodu Clone Et
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Bağımlılıkları Kur
        run: |
          pip install pytest requests  # Gerekli bağımlılıkları buraya ekleyin

      - name: API Testlerini Çalıştır
        run: pytest -v