name: Run Tests and Publish Allure Report to GitHub Pages

on:
  schedule:
    - cron: '38 6,18 * * *'  # Türkiye saatiyle sabah ve akşam 09:38 (UTC+3)
  workflow_dispatch:  # Manuel olarak çalıştırmayı etkinleştirir

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      - name: Kodu Clone Et
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Bağımlılıkları Kur
        run: |
          pip install pytest requests  # Gerekli bağımlılıkları buraya ekleyin

      - name: API Testlerini Çalıştır
        run: pytest -v

      - name: Allure Raporunu Hazırla
        if: success()
        run: |
          mkdir -p allure-report
          allure generate --clean --output allure-report

      - name: Raporu GitHub Pages ile Yayınla
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report