name: Daily API Tests

on:
  schedule:
    - cron: '43 17 * * *'  # Türkiye saatiyle her gün 20:43'te çalışır
  workflow_dispatch:  # Manuel çalıştırma seçeneği

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Clone Et
        uses: actions/checkout@v2

      - name: Python Kur
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Bağımlılıkları Kur
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: API Testlerini Çalıştır
        run: pytest -v