name: Daily API Tests

on:
  schedule:
    - cron: '55 17 * * *'  # Türkiye saatiyle her gün 20:43'te çalışır
  workflow_dispatch:  # Manuel çalıştırma seçeneği ekler

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Clone Et
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Bağımlılıkları Kur
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests  # Gerekli paketleri burada tanımlıyoruz

      - name: API Testlerini Çalıştır
        run: pytest -v