name: Daily API Tests

on:
  schedule:
    - cron: '43 17 * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Burada secret olarak eklenen URL'yi kullanıyoruz

    steps:
      - name: Kodu Clone Et
        uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Bağımlılıkları Kur
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: API Testlerini Çalıştır
        run: pytest -v