name: Run Tests and Publish Allure Report to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '10 7,19 * * *'  # UTC'ye göre sabah ve akşam 09:38 ve 21:38 (Türkiye saati UTC+3)

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install pytest allure-pytest

      - name: Run Tests and Generate Allure Results
        run: |
          pytest --alluredir=allure-results

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report